theme: jekyll-theme-midnight

title: AulasRepo
description: reposit√≥rio de aulas
url: "https://tktictac.tk"

aux_links:
  "Home":
    - "tktictac.tk/tktictak"
aux_links_new_tab: false

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"
